FROM openjdk:12-jdk
LABEL maintainer="jllado@gmail.com"
RUN useradd -ms /bin/bash jenkins
RUN mkdir /app
VOLUME /app
VOLUME /app/.youtube_client_secret.json
VOLUME /root/.gradle
USER jenkins
WORKDIR /app
ENTRYPOINT ["./gradlew", "build", "--no-daemon", "-DupdateTestTimestamps=true", "--scan"]
