version: '3'
services:
  vibot-youtube:
    image: jllado-server:5000/vibot/vibot-youtube:${DEPLOY_VERSION:-latest}
    container_name: vibot-youtube
    volumes:
      - ${YOUTUBE_SECRET_FILE:-./.youtube_client_secret.json}:/.youtube_client_secret.json
    build: .
    ports:
      - "20000:8080"
